### ISSUE TITLE
About Chinese performances. 关于中文能力的询问

### ISSUE THREAD

**Issue by WangRongsheng** [pjlab-sys4nlp/llama-moe#48]
您好，谢谢您发布如此好的工作，我们近期也在mixtral-8x7b上做了微调（我们的项目：https://github.com/WangRongsheng/Aurora ），想知道llama-moe的中文能力如何呢？

**Comment by Spico197** [comment]
Hi，感谢您对我们项目的关注，以及Aurora对中文MoE社区的贡献~ LLaMA-MoE是基于LLaMA-2的，我们没有做中文任务的测试，不过可能需要额外的词表扩充、继续预训练和fine-tune才能提升中文的理解和生成能力。

Hi there, thanks for your attention on this project~ We built LLaMA-MoE on LLaMA-2, so it is expected to have a poor Chinese capability. It may extend the vocabulary and apply extra continual pre-training or fine-tuning to enhance the Chinese understanding and generation.

**Comment by WangRongsheng** [comment]
感谢回复，我们后续会在中文能力上测试llama-moe！
