### ISSUE TITLE
./scripts/expert_construction/split/run_split_random.sh: 行 18: srun: 未找到命令

### ISSUE THREAD

**Issue by 18600709862** [pjlab-sys4nlp/llama-moe#54]
run bash error
./scripts/expert_construction/split/run_split_random.sh: 行 18: srun: 未找到命令

**Comment by 18600709862** [comment]
apt-get install slurm-client
srun: error: resolve_ctls_from_dns_srv: res_nsearch error: Unknown host
srun: error: fetch_config: DNS SRV lookup failed
srun: error: _establish_config_source: failed to fetch config
srun: fatal: Could not establish a configuration source

**Comment by 18600709862** [comment]
srun: unrecognized option '--quotatype=auto'
del
srun: error: Invalid generic resource (gres) specification

**Comment by 18600709862** [comment]
srun: unrecognized option '--quotatype=auto'
del
srun: error: Invalid generic resource (gres) specification

**Comment by 18600709862** [comment]
set
gpus 0 
--partition=mastername
ok thanks

**Comment by Spico197** [comment]
Thanks for using our code~

We use slurm (`sbatch` and `srun` commands) for job queuing in a cluster. You may need to remove those commands for adaptation.
