### ISSUE TITLE
About dataset prepare

### ISSUE THREAD

**Issue by bestfleer** [pjlab-sys4nlp/llama-moe#58]
Hi, thanks for your interesting work. I also need use SlimPajama to fine-tune my model. Can you teach me how to split the whole SlimPajama into separate folders as you listed?
/path_to_data/en_arxiv
/path_to_data/en_book
/path_to_data/en_c4
/path_to_data/en_cc
/path_to_data/en_stack
/path_to_data/en_wikipedia
/path_to_data/github

**Comment by Spico197** [comment]
Sorry for the late response. We get the data from our data team, so the dataset is already prepared.

But I found there're tags in `meta` indicating the data types [here](https://huggingface.co/datasets/cerebras/SlimPajama-627B). Maybe you could write a code snippet to convert the dataset.
