### ISSUE TITLE
please update modeling_llama_moe_hf.py

### ISSUE THREAD

**Issue by Minami-su** [pjlab-sys4nlp/llama-moe#65]
llama2 does not seem to be supported, please update modeling_llama_moe_hf.py

**Comment by Spico197** [comment]
Hi there, thanks for your attention on this project ~

Could you provide more details about the current problem and the version of `transformers` you are using?

**Comment by Minami-su** [comment]
My transformer version is 4.38.1 I use llama2 7b chat model this is my inference code:
```
import torch
from llama_moe.modeling_llama_moe_hf import LlamaMoEForCausalLM
from transformers import AutoTokenizer
model_dir = "petrelfs/share_data/quxiaoye/models/LlamaMoEForCausalLM/Random/Qwen1.5-0.5B-Chat_llamafy-16Select4-gate_proj-Scale1.0"
tokenizer = AutoTokenizer.from_pretrained(model_dir)
model = LlamaMoEForCausalLM.from_pretrained(model_dir, torch_dtype=torch.bfloat16,load_in_4bit=True,device_map="auto")
model.eval()
#model.to("cuda:0")

input_text = "Suzhou is famous of"
inputs = tokenizer(input_text, return_tensors="pt")
inputs = inputs.to("cuda:0")

pred = model.generate(**inputs, max_length=50, temperature=0.1)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```

**Comment by Spico197** [comment]
Thanks for the response. The model directory to `petrelfs/share_data/quxiaoye/models/LlamaMoEForCausalLM/Random/llama2-7B-Chat-16Select4-gate_proj-Scale1.0` seems to be not correct.

Have you split the FFNs to experts from `llama-2-7b-chat-hf` and continually pre-trained the corresponding model to recover language abilities?

**Comment by Minami-su** [comment]
> Thanks for the response. The model directory to `petrelfs/share_data/quxiaoye/models/LlamaMoEForCausalLM/Random/llama2-7B-Chat-16Select4-gate_proj-Scale1.0` seems to be not correct.
> 
> Have you split the FFNs to experts from `llama-2-7b-chat-hf` and continually pre-trained the corresponding model to recover language abilities?

Thank you your response,I'm not pretrain moe model,I will training it next.

**Comment by Spico197** [comment]
After converting the dense model into MoE, you may try to load the model and make text completions, but the prediction quality is not guaranteed, so continual pre-training is needed for language ability recovery.
