### ISSUE TITLE
Some weights of LlamaMoEForCausalLM were not initialized

### ISSUE THREAD

**Issue by Minami-su** [pjlab-sys4nlp/llama-moe#66]
transformer version 4.38.0 
```
import torch
from llama_moe.modeling_llama_moe_hf import LlamaMoEForCausalLM
from transformers import AutoTokenizer

model_dir = "Qwen1.5-0.5B-Chat_llamafy-16Select4-gate_proj-Scale1.0"

model = LlamaMoEForCausalLM.from_pretrained(model_dir, trust_remote_code=True, )
```
Some weights of LlamaMoEForCausalLM were not initialized from the model checkpoint at Qwen1.5-0.5B-Chat_llamafy-16Select4-gate_proj-Scale1.0 and are newly initialized: ['model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.22.self_attn.rotary_emb.inv_freq', 'model.layers.23.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq']

**Comment by Minami-su** [comment]
![image](https://github.com/pjlab-sys4nlp/llama-moe/assets/76865636/8356774d-cf0f-40b5-bac7-ddce10965893)
![image](https://github.com/pjlab-sys4nlp/llama-moe/assets/76865636/ce4f4484-9835-4e2b-829c-e04da96f6a42)

**Comment by Spico197** [comment]
Hi there, thanks for your interest in this project~

`inv_freq` will be re-initialized from scratch each time when we initialize a model. This is NOT expected if you have fine-tuned or changed the `inv_freq`. In that case, this parameter should be in part of the dumpped model weights.

**Comment by Minami-su** [comment]
> Hi there, thanks for your interest in this project~
> 
> `inv_freq` will be re-initialized from scratch each time when we initialize a model. This is NOT expected if you have fine-tuned or changed the `inv_freq`. In that case, this parameter should be in part of the dumpped model weights.

So, this error "" Some weights of LlamaMoEForCausalLM were not initialized" "has no effect?

**Comment by Spico197** [comment]
There are no effects if you don't change this part of weights and could accept its re-initialization. I checked the model weights in `Qwen/Qwen1.5-4B` but found no `inv_freq`. So the re-initialization is a expected behaviour.

**Comment by Minami-su** [comment]
> There are no effects if you don't change this part of weights and could accept its re-initialization. I checked the model weights in `Qwen/Qwen1.5-4B` but found no `inv_freq`. So the re-initialization is a expected behaviour.

Thank you very much. I see.
