### ISSUE TITLE
per_device_train_batch_size=1，but almost all of my GPU memory is still being used up?

### ISSUE THREAD

**Issue by rzr002** [pjlab-sys4nlp/llama-moe#67]
![Uploading 截屏2024-03-09 20.46.01.png…]()
Can you please explain why, when I run the llama2_7b model pre-training on 4*A800 with only the following settings:

per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=1
almost all of my GPU memory is still being used up? I don't think this is reasonable.
![截屏2024-03-09 20 45 25](https://github.com/pjlab-sys4nlp/llama-moe/assets/131580350/f8c0c83f-8e61-4ec2-bdd7-4d639aa0d1c1)
![截屏2024-03-09 20 45 13](https://github.com/pjlab-sys4nlp/llama-moe/assets/131580350/6fec5c52-d971-4c1c-a702-15ed3750c27e)

**Comment by rzr002** [comment]
![Uploading 截屏2024-03-09 20.46.08.png…]()

**Comment by Spico197** [comment]
Hi there, thanks for your interest in llama-moe~

Could you trace the code to check if `flash_attn` is properly set up? (like printing a message)

https://github.com/pjlab-sys4nlp/llama-moe/blob/ce1b1323fbfbdc3a1440dc1b2a2b9e625e2678bc/smoe/modules/flash_attn.py#L116

**Comment by rzr002** [comment]
> Hi there, thanks for your interest in llama-moe~
> 
> Could you trace the code to check if `flash_attn` is properly set up? (like printing a message)
> 
> https://github.com/pjlab-sys4nlp/llama-moe/blob/ce1b1323fbfbdc3a1440dc1b2a2b9e625e2678bc/smoe/modules/flash_attn.py#L116



> Hi there, thanks for your interest in llama-moe~
> 
> Could you trace the code to check if `flash_attn` is properly set up? (like printing a message)
> 
> https://github.com/pjlab-sys4nlp/llama-moe/blob/ce1b1323fbfbdc3a1440dc1b2a2b9e625e2678bc/smoe/modules/flash_attn.py#L116

Yep, I checked and find something wrong:
I print(moudle
<img width="580" alt="截屏2024-03-10 01 07 16" src="https://github.com/pjlab-sys4nlp/llama-moe/assets/131580350/04d7b155-ff57-4396-af7c-809794fa26a5">
)
results are 
"module: LlamaAttention(
  (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
  (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
  (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
  (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
  (rotary_emb): LlamaRotaryEmbedding()
)
module: Linear(in_features=4096, out_features=4096, bias=False)
module: Linear(in_features=4096, out_features=4096, bias=False)
module: Linear(in_features=4096, out_features=4096, bias=False)
module: Linear(in_features=4096, out_features=4096, bias=False)
module: LlamaRotaryEmbedding()
module: LlamaMLP(
  (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
  (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
  (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
  (act_fn): SiLUActivation()
)"

**Comment by rzr002** [comment]
<img width="606" alt="截屏2024-03-10 01 12 07" src="https://github.com/pjlab-sys4nlp/llama-moe/assets/131580350/44f8e293-150c-4461-bcdc-9b17b3db5d82">
When I use this code to force into the “            module.forward = MethodType(llama_flash_attention, module)
”，it still not work with the gpu memory

**Comment by rzr002** [comment]
<img width="695" alt="截屏2024-03-10 01 18 43" src="https://github.com/pjlab-sys4nlp/llama-moe/assets/131580350/830d3c4d-c198-456a-9914-eca9bb913bda">
I would be immensely grateful for your help.

**Comment by Spico197** [comment]
Hi there, I've checked the normal SFT on llama2-7b, and get the same GPU consumption as yours. So I don't see any problems in the GPU memory consumption. If you want to save more memories, feel free to change ZeRO-1 to ZeRO-3/FSDP w/ full_shard.

**Comment by rzr002** [comment]
> Hi there, I've checked the normal SFT on llama2-7b, and get the same GPU consumption as yours. So I don't see any problems in the GPU memory consumption. If you want to save more memories, feel free to change ZeRO-1 to ZeRO-3/FSDP w/ full_shard.

ok,thanks for you help
