### ISSUE TITLE
Code on Expert Specialization Experiments

### ISSUE THREAD

**Issue by Tangkexian** [pjlab-sys4nlp/llama-moe#71]
Great work! And I am particularly interested in the section about "Expert Specialization". 

I am reaching out to inquire if there is any publicly available code or additional material related to the experiments conducted in this section of the paper?  Alternatively, if the code is not available, any additional insights or tips on replicating the experiments would also be extremely helpful.

Thank you !

<img width="405" alt="Snipaste_2024-10-24_16-39-07" src="https://github.com/user-attachments/assets/d26507fa-e925-41ab-a80a-cca9e5fb5d80">

**Comment by XiaoYee** [comment]
@Spico197  Please help

**Comment by Spico197** [comment]
Hi there, thanks for your attention to our work~

You may check the code here to reproduce the visualization on gate loads:

https://github.com/pjlab-sys4nlp/llama-moe/blob/b17aff436cce58e2fcd7327789c7fadafe15d19e/smoe/entrypoint/analysis/gate_load_vis.py#L108-L116
